name = "Naively Optimized"
author = "DoggoNako"
version = "mr1.20.2-1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8523015b66a1a36fb7faf3ed200e1a4eccf75507025d22ba01426f9aa41ed69d"

[versions]
minecraft = "1.20.2"
neoforge = "20.2.88"
