name = "Naively Optimized"
author = "DoggoNako"
version = "mr1.20.6-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0ae1fc8942ab4c352977036d7f449c8a7de2870d6ac552e031300bece37f544"

[versions]
minecraft = "1.20.6"
neoforge = "20.6.121"
