name = "Naively Optimized"
author = "DoggoNako"
version = "mr1.20.5-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea8a537f7904572fba3a88a63d3f9b9e2c67973b2091fda1b144213050d2ae1d"

[versions]
minecraft = "1.20.5"
neoforge = "20.5.21-beta"
